### ISSUE TITLE
wnn_1 (RNA/ATAC joint profiling in integrated space) raises an error in combine.Rmd 

### ISSUE THREAD

**Issue by Mira0507** [NICHD-BSPC/multiome-wf#7]
I got two `wnn`s using `weighted_nn` from the following configuration (`config.yaml`):

```yaml
weighted_nn:
  activate: true
  groups:
    wnn_0:
      neighbor_method: weighted
      input_groups:
        - unintegrated_0 # corresponds to SCT
        - unintegrated_1 # corresponds to Peaks
      # assay_name:
      # - Gene.Expression # or SCT
      # - Peaks
      reduction:
      - pca
      - lsi
      umap_dims:
      - - 1
        - 25
      - - 1
        - 20
      resolution: 0.8
    wnn_1:
      neighbor_method: weighted
      input_groups:
        - integrated_0 # corresponds to SCT
        - integrated_1 # corresponds to Peaks
      # assay_name:
      # - Gene.Expression # or SCT
      # - Peaks
      reduction:
      - integrated_pca
      - integrated_lsi
      umap_dims:
      - - 1
        - 25
      - - 1
        - 20
      resolution: 0.8
```

These objs raised an error in the rule `combine` (run by `combine.Rmd`) here: 
https://github.com/NICHD-BSPC/multiome-wf/blob/afa957e7a6b01dd6069a59ddf66aa930021a3d19/workflow/combine.Rmd#L269-L282

Specifically, `Key(seurat_main[[assay_new]]) = assay_new` raises an error `“Cannot find ‘wnn_1’ in this Seurat Object”` with `wnn_1`. I figured out that `assay_new` is set to `wnn_1` here. I'm assuming `wnn_1` should have been added to the obj `seurat_main` in the previous if statement so the key can be updated (`Key(seurat_main[[assay_new]]) = assay_new `) in the following if statement. Somehow it only happens with `wnn_1` whereas `wnn_0` has no problem with those if statements. 

My temporary fixation is to add `tryCatch` adding `seurat_main[[assay_new]] <- seurat_add[[seurat_add@active.assay]]` in cases where the `seurat_main` didn't acquire `wnn_1` in the previous if statement.

```r
        if (any(grepl("integrated", names(seurat_add@reductions)))) {
          tryCatch(
              expr={
                  Key(seurat_main[[assay_new]]) = assay_new
              },
              error=function(e) {
                  seurat_main[[assay_new]] <- seurat_add[[seurat_add@active.assay]]  # add a new assay if absent
                  Key(seurat_main[[assay_new]]) = assay_new
            })
        }
```

This trick seems to work error-free in R. I'm double-checking whether it's also error-free when running in snakemake.
