### ISSUE TITLE
QC filtering not performed at lower limit

### ISSUE THREAD

**Issue by Mira0507** [NICHD-BSPC/multiome-wf#9]
Filtering set in the `config.yaml`

```yaml
qc:
  remove_outliers: true
  rm_outliers_method: sd
  meta_labels:
  - nCount_Gene.Expression
  - nCount_Peaks
  - percent.mt
  - TSS.enrichment
  lower:
    nCount_Gene.Expression: 100
    nCount_Peaks: 1000
    TSS.enrichment: 2
  upper: null
```

Current filtering recap:

- lower limit:
    - number of reads in RNA: 100
    - number of reads in ATAC: 1000
    - TSS enrichment: 2
    - percent mito: 1
- upper limit:
    - if `rm_outliers_method` set to `sd`: **mean + 3*sd (CURRENT SETTING)**
    - if `rm_outliers_method` set to `iqr`: 3Q + 2.2*IQR

Unlike above settings, the seurat obj still shows many cells below the lower limits as shown here:
![filtering](https://user-images.githubusercontent.com/57876673/215579129-e92c2e90-c650-46c1-9374-0386e7e796e7.png)

- `nCount_Gene.Expression` (number of reads in RNA set to 100) = 27
- `nCount_peaks` (number of reads in ATAC set to 1000) = 122
- `TSS.enrichment` (TSS enrichment set to 2) = 0.067

It's also recapped by my boxplot where upper and lower limits are indicated by red horizontal lines:

<img width="222" alt="vis" src="https://user-images.githubusercontent.com/57876673/215579357-01609816-36db-4c62-9510-c715340d3944.png">

Despite that this was observed in the E15 dataset, unfiltered cells below lower limits were discovered in E12 in the same way. 

We need to fix the filtering code [here](https://github.com/NICHD-BSPC/multiome-wf/blob/main/workflow/qc.Rmd#L188).
